# Generated by Django 2.2 on 2019-07-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industrydetailsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='email',
        ),
    ]
