# Generated by Django 2.2 on 2019-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrydetailsapp', '0002_remove_company_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='email',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
