# Generated by Django 2.2 on 2019-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrydetailsapp', '0004_auto_20190713_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='built_area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='core_operation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='factory_time_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='factory_time_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='founded_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='keycontact',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='number_of_employees',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='office_time_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='office_time_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='overall_area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='shop_area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='website',
            field=models.CharField(max_length=70),
        ),
    ]
