# Generated by Django 2.2 on 2019-07-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrydetailsapp', '0005_auto_20190713_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='number_of_employees',
            field=models.IntegerField(),
        ),
    ]
